In [ ]:
from google.colab import drive
import os
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Joe's cell
DRIVE_PATH = '/content/drive/MyDrive/Cal/Colab/DeepMusicVisualizer'

In [ ]:
# Richard's cell
DRIVE_PATH = '/content/drive/MyDrive/cs194/DeeperMusicVisualizer'

In [ ]:
SYM_PATH = '/content/DeepMusicVisualizer'
if not os.path.exists(SYM_PATH):
  !ln -s $DRIVE_PATH $SYM_PATH

In [ ]:
import numpy as np
%load_ext autoreload
%autoreload 2

In [ ]:
file_path = os.path.join(SYM_PATH, 'convert_rhythm_output/rhythm_data_faded_128_50epochs_hardcoded_alltiming.npz')
data = np.load(file_path)

In [ ]:
objs = data['objs']
predictions = data['predictions']
ticks = data['ticks']
timestamps = data['timestamps']
is_slider = data['is_slider']
is_spinner = data['is_spinner']
is_note_end = data['is_note_end']
sv = data['sv']
slider_ticks = data['slider_ticks']
dist_multiplier = data['dist_multiplier']

In [ ]:
result = []
sliding = False;
for i, pred in enumerate(predictions):
  if pred[2]==1: #slider
    slide_ticks = slider_ticks[i]
    if i == len(predictions) - 1:
      slide_ms = 1000
    elif ticks[i+1] - ticks[i] > 0:
      ms_gap = timestamps[i+1] - timestamps[i]
      slide_ms = slide_ticks / (ticks[i+1] - ticks[i]) * ms_gap
    else:
      ms_gap = timestamps[i+1] - timestamps[i]
      slide_ms = slide_ticks / (4) * ms_gap
    if sliding==False or i==len(predictions) - 1:
      result.append([timestamps[i], 1, slide_ms])
    else:
      result[-1][2] += slide_ms
    if i!=len(predictions) - 1 and ticks[i+1] - ticks[i] == slide_ticks:
      print('continuing slide')
      sliding = True;
  elif pred[1]==1: #note
    sliding=False;
    result.append([timestamps[i], 0, 0])
  else:
    print("Error")

Error
Error
Error


In [ ]:
print(result)

[[130, 1, 666.5], [1463, 1, 667.0], [2797, 1, 1333.3333333333333], [4797, 0, 0], [5130, 1, 333.3333333333333], [6130, 1, 333.5], [6797, 1, 333.0], [7463, 1, 333.5], [8130, 1, 666.6666666666666], [9130, 1, 333.3333333333333], [10130, 0, 0], [10797, 1, 666.5], [12130, 1, 333.5], [12797, 1, 333.0], [13463, 1, 666.6666666666666], [14463, 0, 0], [14797, 1, 666.5], [16130, 1, 333.5], [16797, 1, 666.5], [18130, 1, 333.5], [18797, 1, 666.6666666666666], [19797, 1, 333.0], [20463, 1, 333.3333333333333], [22130, 1, 666.6666666666666], [23130, 1, 333.5], [23797, 1, 333.0], [24463, 1, 333.5], [25130, 1, 333.3333333333333], [26130, 1, 666.5], [27463, 1, 333.5], [28130, 1, 666.6666666666666], [29130, 1, 333.3333333333333], [30130, 1, 666.6666666666666], [31130, 0, 0], [31463, 1, 331.75], [32790, 1, 666.5], [34123, 1, 333.5], [34790, 1, 666.5], [36123, 0, 0], [36790, 1, 666.5], [38123, 1, 333.5], [38790, 1, 333.0], [39456, 1, 666.8000000000001], [41123, 1, 333.3333333333333], [42123, 1, 333.5], [4279

In [ ]:
np.save('/content/DeepMusicVisualizer/data/beatmaps_57/Faded/output_128_50epochs_hardcoded_alltiming.npy', result)

In [ ]:
for i, val in enumerate(ticks):
  if val == 0:
    print(i, sv[i])
print(timestamps[1]-timestamps[0])
print(timestamps[42]-timestamps[41])
print(timestamps[295]-timestamps[294])
print(sv)

0 260.0
39 130.0
70 195.00000000000048
219 195.00000000000048
286 130.0
292 130.0
293 260.0
667
667
2400
[260.  260.  260.  260.  260.  260.  260.  260.  260.  260.  260.  260.
 260.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.
 130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.
 130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.
 130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.  130.
 130.  130.  130.  130.  130.  130.  130.  130.  130.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  130.  195.  195.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  195.
 195.  195.  195.  195.  195.  195.  195.  195.  195.  195.  130.  130.
 130.  130.  130.  130.  130.  

In [ ]:
print('objs', objs)
print('predictions', predictions)
print('ticks', ticks)
print('timestamps', timestamps)
print('is_slider', is_slider)
print('is_spinner', is_spinner)
print('is_note_end', is_note_end)
print('sv', sv)
print('slider_ticks', slider_ticks)
print('dist_multiplier', dist_multiplier)

objs [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
predictions [[1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 ...
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]
ticks [  0   4   8  12  16  20  24  32  36  40  48  56  60  68  72  76  80  84
  88  96 100 108 112 116 120 124 128 136 140 144 148 152 156 160 168 172
 176 180 184   0   4   8  12  16  20  24  28  32  36  40  44  48  56  60
  64  68  76  80  84  88  92  96 100 104 10

In [ ]:
print('objs', objs.shape)
print('predictions', predictions.shape)
print('ticks', ticks.shape)
print('timestamps', timestamps.shape)
print('is_slider', is_slider.shape)
print('is_spinner', is_spinner.shape)
print('is_note_end', is_note_end.shape)
print('sv', sv.shape)
print('slider_ticks', slider_ticks.shape)
print('dist_multiplier', dist_multiplier.shape)

objs (296,)
predictions (296, 5)
ticks (296,)
timestamps (296,)
is_slider (296,)
is_spinner (296,)
is_note_end (296,)
sv (296,)
slider_ticks (296,)
dist_multiplier ()


In [ ]:
for pred in predictions:
  setset[str(pred)] = 1

In [ ]:
setset

{'[1. 0. 1. 0. 0.]': 1, '[1. 0. 1. 0. 1.]': 1, '[1. 1. 0. 0. 1.]': 1}

In [ ]:
for i,t in enumerate(slider_ticks):
  if t == 4 and i != len(slider_ticks):
    tick_gap = ticks[i+1] - ticks[i]
    print(tick_gap)

8
8
8
8
8
8
8
8
-184
8
8
8
8
6
6
8
8
6
8
8
8
8
7
8
8
8
-32
8


In [ ]:
a = 0
b = 0
c = 0
for i, pred in enumerate(predictions):
  if pred[2]==1 and pred[4]==0:
    a+=1
  elif pred[2]==1 and pred[4]==1:
    b+=1
  elif pred[1]==1:
    c+=1
  else:
    print("Error")

In [ ]:
print(a,b,c)

57 215 24
